###

GET http://localhost:3000/


###
POST http://localhost:3000/post
Content-Type: application/json

{
  "title": "The Matrix",
  "content": "A computer hacker learns about the true nature of his reality.",
  "sender": "The Wachowskis"
}

###
GET http://localhost:3000/post/69389c7b9b8da04029b13eea

###
DELETE http://localhost:3000/post/69389c7b9b8da04029b13eea

###
PUT http://localhost:3000/post/69389c7b9b8da04029b13eea
Content-Type: application/json  

{
  "title": "Inception",
  "content": "A mind-bending thriller about dreams within dreams.",
  "sender": "Christopher Nolan"
}