###

GET http://localhost:3000/


###
POST http://localhost:3000/movie
Content-Type: application/json  

{
  "title": "Inception",
  "year": 2010
}

###
GET http://localhost:3000/movie/69387a43f2d9e5aab8c14706

###
DELETE http://localhost:3000/movie/69387a43f2d9e5aab8c14706

###
PUT http://localhost:3000/movie/69149147288d1775ac1bd336
Content-Type: application/json  

{
  "title": "Inception",
  "year": 2013
}